export default {
  index: "Home",
  "why-rhesis": "Why Rhesis?",
  "getting-started": "Getting Started",
  concepts: "Core Concepts",
  deployment: "Deployment",
  platform: "Platform",
  sdk: "SDK",
  tracing: "Tracing",
  "conversation-simulation": "Conversation Simulation",
  "adversarial-testing": "Adversarial Testing",
  "multimodal-testing": "Multi-modal Testing",
  frameworks: "Frameworks",
  development: "Development",
  "---": {
    type: "separator",
  },
  guides: "Guides",
  glossary: "Glossary",
  contributing: "Contributing",
  acknowledgments: "Acknowledgments",
  sdk_reference: {
    title: "SDK Reference",
    href: "https://rhesis-sdk.readthedocs.io/en/latest/",
  },
};
