apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- networkpolicy.yaml
- hpa.yaml

labels:
- includeSelectors: true
  pairs:
    environment: dev

# Namespace will be dynamically set by GitHub workflow during deployment
# Dev: rhesis-worker-dev, Staging: rhesis-worker-stg, Production: rhesis-worker
namespace: rhesis-worker-dev

images:
- name: gcr.io/PROJECT_ID/rhesis-worker
  newTag: latest 