apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- networkpolicy.yaml

commonLabels:
  environment: dev

# Namespace will be set via command line during deployment
namespace: rhesis-worker

images:
- name: gcr.io/PROJECT_ID/rhesis-worker
  newTag: latest 