backends:
  deepeval:
    module: "rhesis.backend.metrics.deepeval_metrics"
    factory: "DeepEvalMetricFactory"
  ragas:
    module: "rhesis.backend.metrics.ragas_metrics"
    factory: "RagasMetricFactory"
  rhesis:
    module: "rhesis.backend.metrics.rhesis_metrics"
    factory: "RhesisMetricFactory" 