backends:
  deepeval:
    module: "rhesis.backend.metrics.deepeval"
    factory: "DeepEvalMetricFactory"
  ragas:
    module: "rhesis.backend.metrics.ragas"
    factory: "RagasMetricFactory"
  rhesis:
    module: "rhesis.backend.metrics.rhesis"
    factory: "RhesisMetricFactory" 