metrics:
  answer_relevancy:
    backend: deepeval
    default_threshold: 0.5
    description: "Measures how relevant the answer is to the question"
    requires_ground_truth: true

  faithfulness:
    backend: deepeval
    default_threshold: 0.5
    description: "Measures how faithful the answer is to the provided context"
    requires_ground_truth: false

  contextual_relevancy:
    backend: deepeval
    default_threshold: 0.5
    description: "Measures how relevant the context is to the question"
    requires_ground_truth: false

  contextual_precision:
    backend: deepeval
    default_threshold: 0.5
    description: "Measures the precision of context usage in the answer"
    requires_ground_truth: false

  contextual_recall:
    backend: deepeval
    default_threshold: 0.5
    description: "Measures how much of the relevant context is used"
    requires_ground_truth: false

backends:
  deepeval:
    module: "rhesis.metrics.deepeval_metrics"
    factory: "DeepEvalMetricFactory" 