from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "078d2d5b5f9e"
down_revision: Union[str, None] = "e8dd05d20cd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metric", sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "metric",
        sa.Column("passing_categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric", "passing_categories")
    op.drop_column("metric", "categories")
    # ### end Alembic commands ###
