from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import rhesis.backend.app.models.guid
from rhesis.backend.alembic.utils.template_loader import (
    load_cleanup_status_template,
    load_cleanup_type_lookup_template,
    load_status_template,
    load_type_lookup_template,
)

# revision identifiers, used by Alembic.
revision: str = "1010fc534974"
down_revision: Union[str, None] = "c5f354e261ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        load_type_lookup_template("""
        ('EmbeddingDimension', '384', '384-dimensional embeddings'),
        ('EmbeddingDimension', '768', '768-dimensional embeddings'),
        ('EmbeddingDimension', '1024', '1024-dimensional embeddings'),
        ('EmbeddingDimension', '1536', '1536-dimensional embeddings'),
        ('EmbeddingOrigin', 'user', 'Embedding created from user-provided content'),
        ('EmbeddingOrigin', 'generated', 'Embedding automatically generated by the system'),
        ('EmbeddingOrigin', 'imported', 'Embedding imported from external source')
    """)
    )

    op.execute(
        load_status_template(
            type_name="EntityType",
            entity_type="Embedding",
            status_values_clause="""
            ('Active', 'Embedding is active and usable'),
            ('Stale', 'Embedding outdated due to text or model configuration changes')
        """,
        )
    )

    # 1. Drop partial indexes that reference the legacy 'status' string column before dropping it.
    # PostgreSQL forbids dropping a column that is referenced by an index.
    op.drop_index("idx_active_model_config", table_name="embedding")
    op.drop_index("idx_active_entity_model_config", table_name="embedding")

    # 2. Add status_id column to embedding
    op.add_column(
        "embedding",
        sa.Column("status_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
    )
    op.create_foreign_key("fk_embedding_status_id", "embedding", "status", ["status_id"], ["id"])

    # 3. Make status_id non-nullable and drop legacy string status column
    # (No data backfill is needed because the table is guaranteed to be empty at this point)
    op.alter_column("embedding", "status_id", nullable=False)
    op.drop_column("embedding", "status")

    # 4. Recreate as composite indexes including status_id.
    # Partial indexes with subqueries are forbidden by PostgreSQL; status_id is now a FK UUID
    # that varies per organization, so we include it as a regular index column instead.
    op.create_index(
        "idx_active_model_config", "embedding", ["model_id", "config_hash", "status_id"]
    )
    op.create_index(
        "idx_active_entity_model_config",
        "embedding",
        ["entity_type", "model_id", "config_hash", "status_id"],
    )


def downgrade() -> None:
    # 1. Drop composite indexes before restoring the legacy string status column
    op.drop_index("idx_active_model_config", table_name="embedding")
    op.drop_index("idx_active_entity_model_config", table_name="embedding")

    # 2. Add back the legacy string status column
    op.add_column(
        "embedding",
        sa.Column("status", sa.String(length=20), server_default="active", nullable=True),
    )

    # 3. Make string status non-nullable
    # (No data backfill is needed because the table is guaranteed to be empty at this point)
    op.alter_column("embedding", "status", nullable=False)

    # 4. Drop status_id column
    op.drop_constraint("fk_embedding_status_id", "embedding", type_="foreignkey")
    op.drop_column("embedding", "status_id")

    # 5. Recreate original partial indexes referencing the restored string status column
    op.execute(
        "CREATE INDEX idx_active_model_config ON embedding (model_id, config_hash)"
        " WHERE status = 'active'"
    )
    op.execute(
        "CREATE INDEX idx_active_entity_model_config ON embedding"
        " (entity_type, model_id, config_hash) WHERE status = 'active'"
    )

    op.execute(
        load_cleanup_status_template(
            type_name="EntityType",
            entity_type="Embedding",
            status_names_clause="""
            ('Active'),
            ('Stale')
        """,
        )
    )

    op.execute(
        load_cleanup_type_lookup_template(
            type_name="EmbeddingDimension",
            type_values_clause="""
            ('384'), ('768'), ('1024'), ('1536')
        """,
        )
    )

    op.execute(
        load_cleanup_type_lookup_template(
            type_name="EmbeddingOrigin",
            type_values_clause="""
            ('user'), ('generated'), ('imported')
        """,
        )
    )
