from typing import Sequence, Union

from alembic import op

from rhesis.backend.app.migrations.utils.template_loader import (
    load_cleanup_status_template,
    load_cleanup_type_lookup_template,
    load_status_template,
    load_type_lookup_template,
)

# revision identifiers, used by Alembic.
revision: str = "1010fc534974"
down_revision: Union[str, None] = "8993eecbb913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        load_type_lookup_template("""
        ('EmbeddingDimension', '384', '384-dimensional embeddings'),
        ('EmbeddingDimension', '768', '768-dimensional embeddings'),
        ('EmbeddingDimension', '1024', '1024-dimensional embeddings'),
        ('EmbeddingDimension', '1536', '1536-dimensional embeddings'),
        ('EmbeddingOrigin', 'user', 'Embedding created from user-provided content'),
        ('EmbeddingOrigin', 'generated', 'Embedding automatically generated by the system'),
        ('EmbeddingOrigin', 'imported', 'Embedding imported from external source')
    """)
    )

    op.execute(
        load_status_template(
            type_name="EntityType",
            entity_type="Embedding",
            status_values_clause="""
            ('Active', 'Embedding is active and usable'),
            ('Stale', 'Embedding outdated due to text or model configuration changes')
        """,
        )
    )


def downgrade() -> None:
    op.execute(
        load_cleanup_status_template(
            type_name="EntityType",
            entity_type="Embedding",
            status_names_clause="""
            ('Active'),
            ('Stale')
        """,
        )
    )

    op.execute(
        load_cleanup_type_lookup_template(
            type_name="EmbeddingDimension",
            type_values_clause="""
            ('384'), ('768'), ('1024'), ('1536')
        """,
        )
    )

    op.execute(
        load_cleanup_type_lookup_template(
            type_name="EmbeddingOrigin",
            type_values_clause="""
            ('user'), ('generated'), ('imported')
        """,
        )
    )
