from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "17eaea1d50ed"
down_revision: Union[str, None] = "550fb77f04b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("emojis", sa.JSON(), nullable=True),
        sa.Column("entity_id", rhesis.backend.app.models.guid.GUID(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column(
            "id",
            rhesis.backend.app.models.guid.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nano_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("user_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_id"), "comment", ["id"], unique=True)

    # Add indexes for better query performance
    op.create_index("ix_comment_entity_id", "comment", ["entity_id"])
    op.create_index("ix_comment_entity_type", "comment", ["entity_type"])
    op.create_index("ix_comment_user_id", "comment", ["user_id"])
    op.create_index("ix_comment_organization_id", "comment", ["organization_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_comment_organization_id", table_name="comment")
    op.drop_index("ix_comment_user_id", table_name="comment")
    op.drop_index("ix_comment_entity_type", table_name="comment")
    op.drop_index("ix_comment_entity_id", table_name="comment")
    op.drop_index(op.f("ix_comment_id"), table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
