from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence



# revision identifiers, used by Alembic.
revision: str = '1d482debe2c1'
down_revision: Union[str, None] = '795647de9026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('context_required', sa.Boolean(), nullable=True))
    op.add_column('metric', sa.Column('class_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric', 'class_name')
    op.drop_column('metric', 'context_required')
    # ### end Alembic commands ###