from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import rhesis.backend

# revision identifiers, used by Alembic.
revision: str = "27a49ad77826"
down_revision: Union[str, None] = "8c4ee11cba2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "status", sa.Column("entity_type_id", rhesis.app.models.guid.GUID(), nullable=True)
    )
    op.create_foreign_key(None, "status", "type_lookup", ["entity_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "status", type_="foreignkey")
    op.drop_column("status", "entity_type_id")
    # ### end Alembic commands ###
