from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import rhesis.backend

# revision identifiers, used by Alembic.
revision: str = "40025f477fae"
down_revision: Union[str, None] = "f54a66706856"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_set", sa.Column("owner_id", rhesis.backend.app.models.guid.GUID(), nullable=True)
    )
    op.add_column(
        "test_set", sa.Column("assignee_id", rhesis.backend.app.models.guid.GUID(), nullable=True)
    )
    op.add_column("test_set", sa.Column("priority", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "test_set", "user", ["owner_id"], ["id"])
    op.create_foreign_key(None, "test_set", "user", ["assignee_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "test_set", type_="foreignkey")
    op.drop_constraint(None, "test_set", type_="foreignkey")
    op.drop_column("test_set", "priority")
    op.drop_column("test_set", "assignee_id")
    op.drop_column("test_set", "owner_id")
    # ### end Alembic commands ###
