"""restore comment and task organization_id indexes

An earlier autogenerated migration (792098eebe5f_add_task_model.py) dropped
ix_comment_entity_id, ix_comment_entity_type, ix_comment_user_id and
ix_comment_organization_id -- all four created two migrations prior in
17eaea1d50ed_adding_comment_support.py -- and nothing since has restored
organization_id coverage on either table. Every read of comment or task goes
through the tenant_isolation RLS policy's `organization_id = ...` predicate;
without this index the only usable one is (entity_id, entity_type), which
doesn't help an org-scoped query that isn't also scoped to one entity (e.g.
the Tasks screen's own list view).

Revision ID: 42f4cf7014a0
Revises: 105b0268e6a4
Create Date: 2026-08-31
"""

from typing import Sequence, Union

from alembic import op

revision: str = "42f4cf7014a0"
down_revision: Union[str, None] = "105b0268e6a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

INDEXES = [
    ("ix_comment_organization_id", "comment", ["organization_id"]),
    ("ix_task_organization_id", "task", ["organization_id"]),
]


def upgrade() -> None:
    for name, table, columns in INDEXES:
        op.create_index(name, table, columns)


def downgrade() -> None:
    for name, table, _columns in reversed(INDEXES):
        op.drop_index(name, table_name=table)
