from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4822dd94faa7"
down_revision: Union[str, None] = "7c7b39dbf2ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "endpoint",
        sa.Column("request_headers", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("endpoint", "headers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "endpoint",
        sa.Column(
            "headers", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("endpoint", "request_headers")
    # ### end Alembic commands ###
