from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import rhesis.backend

# revision identifiers, used by Alembic.
revision: str = "579ff09f50ae"
down_revision: Union[str, None] = "e0cd830321a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "type_lookup",
        sa.Column("type_name", sa.String(), nullable=True),
        sa.Column("type_value", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "id",
            rhesis.backend.app.models.guid.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_type_lookup_id"), "type_lookup", ["id"], unique=True)
    op.add_column(
        "category",
        sa.Column("entity_type_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "category", "type_lookup", ["entity_type_id"], ["id"])
    op.drop_column("category", "entity_type")
    op.add_column(
        "response_pattern",
        sa.Column("response_pattern_type_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
    )
    op.create_foreign_key(
        None, "response_pattern", "type_lookup", ["response_pattern_type_id"], ["id"]
    )
    op.drop_column("response_pattern", "response_type")
    op.add_column(
        "topic", sa.Column("entity_type_id", rhesis.backend.app.models.guid.GUID(), nullable=True)
    )
    op.create_foreign_key(None, "topic", "type_lookup", ["entity_type_id"], ["id"])
    op.drop_column("topic", "entity_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic", sa.Column("entity_type", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "topic", type_="foreignkey")
    op.drop_column("topic", "entity_type_id")
    op.add_column(
        "response_pattern",
        sa.Column("response_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "response_pattern", type_="foreignkey")
    op.drop_column("response_pattern", "response_pattern_type_id")
    op.add_column(
        "category", sa.Column("entity_type", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "category", type_="foreignkey")
    op.drop_column("category", "entity_type_id")
    op.drop_index(op.f("ix_type_lookup_id"), table_name="type_lookup")
    op.drop_table("type_lookup")
    # ### end Alembic commands ###
