from typing import Sequence, Union

import rhesis
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ac5d119bda1"
down_revision: Union[str, None] = "624ea7c81723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fill NULL values with placeholder data before setting NOT NULL constraint
    op.execute("UPDATE demographic SET name = 'Unnamed Demographic' WHERE name IS NULL")
    op.execute("UPDATE dimension SET name = 'Unnamed Dimension' WHERE name IS NULL")

    op.alter_column("demographic", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("dimension", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "endpoint",
        "auth_token",
        existing_type=sa.TEXT(),
        type_=rhesis.backend.app.utils.encryption.EncryptedString(),
        existing_nullable=True,
    )
    op.alter_column(
        "endpoint",
        "client_secret",
        existing_type=sa.TEXT(),
        type_=rhesis.backend.app.utils.encryption.EncryptedString(),
        existing_nullable=True,
    )
    op.alter_column(
        "endpoint",
        "last_token",
        existing_type=sa.TEXT(),
        type_=rhesis.backend.app.utils.encryption.EncryptedString(),
        existing_nullable=True,
    )
    op.drop_constraint("uq_tag_name_organization", "tag", type_="unique")
    op.drop_constraint("uq_tagged_item_assignment", "tagged_item", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_tagged_item_assignment",
        "tagged_item",
        ["tag_id", "entity_id", "entity_type", "organization_id"],
    )
    op.create_unique_constraint("uq_tag_name_organization", "tag", ["name", "organization_id"])
    op.alter_column(
        "endpoint",
        "last_token",
        existing_type=rhesis.backend.app.utils.encryption.EncryptedString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "endpoint",
        "client_secret",
        existing_type=rhesis.backend.app.utils.encryption.EncryptedString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "endpoint",
        "auth_token",
        existing_type=rhesis.backend.app.utils.encryption.EncryptedString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column("dimension", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("demographic", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
