from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7793fc8291ab"
down_revision: Union[str, None] = "7bacdb1ce615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("token", sa.Column("last_used_at", sa.DateTime(), nullable=True))
    op.add_column("token", sa.Column("last_refreshed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token", "last_refreshed_at")
    op.drop_column("token", "last_used_at")
    # ### end Alembic commands ###
