from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "792098eebe5f"
down_revision: Union[str, None] = "17eaea1d50ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assignee_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("status_id", rhesis.backend.app.models.guid.GUID(), nullable=False),
        sa.Column("priority_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("entity_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("task_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id",
            rhesis.backend.app.models.guid.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nano_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("user_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["type_lookup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_id"), "task", ["id"], unique=True)
    op.drop_index("ix_comment_entity_id", table_name="comment")
    op.drop_index("ix_comment_entity_type", table_name="comment")
    op.drop_index("ix_comment_organization_id", table_name="comment")
    op.drop_index("ix_comment_user_id", table_name="comment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_comment_user_id", "comment", ["user_id"], unique=False)
    op.create_index("ix_comment_organization_id", "comment", ["organization_id"], unique=False)
    op.create_index("ix_comment_entity_type", "comment", ["entity_type"], unique=False)
    op.create_index("ix_comment_entity_id", "comment", ["entity_id"], unique=False)
    op.drop_index(op.f("ix_task_id"), table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
