from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence



# revision identifiers, used by Alembic.
revision: str = '795647de9026'
down_revision: Union[str, None] = '061018260cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('backend_type_id', rhesis.backend.app.models.guid.GUID(), nullable=True))
    op.create_foreign_key(None, 'metric', 'type_lookup', ['backend_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metric', type_='foreignkey')
    op.drop_column('metric', 'backend_type_id')
    # ### end Alembic commands ###