from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence



# revision identifiers, used by Alembic.
revision: str = '88f39c501875'
down_revision: Union[str, None] = 'b9c0c154a4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evaluation_prompt', sa.Text(), nullable=False),
    sa.Column('evaluation_steps', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('score_type', sa.String(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('ground_truth_required', sa.Boolean(), nullable=True),
    sa.Column('metric_type_id', rhesis.backend.app.models.guid.GUID(), nullable=True),
    sa.Column('status_id', rhesis.backend.app.models.guid.GUID(), nullable=True),
    sa.Column('assignee_id', rhesis.backend.app.models.guid.GUID(), nullable=True),
    sa.Column('owner_id', rhesis.backend.app.models.guid.GUID(), nullable=True),
    sa.Column('id', rhesis.backend.app.models.guid.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nano_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', rhesis.backend.app.models.guid.GUID(), nullable=True),
    sa.Column('organization_id', rhesis.backend.app.models.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['type_lookup.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_id'), 'metric', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_id'), table_name='metric')
    op.drop_table('metric')
    # ### end Alembic commands ###