from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "946a0da4f7bd"
down_revision: Union[str, None] = "f164d8d04e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Fix NULL organization_ids and user_ids in behavior_metric_association table

    # Fix NULL organization_ids using metric's organization_id
    op.execute("""
        UPDATE behavior_metric 
        SET organization_id = m.organization_id
        FROM metric m 
        WHERE behavior_metric.metric_id = m.id 
        AND behavior_metric.organization_id IS NULL
    """)

    # Fix NULL user_ids using metric's owner_id
    op.execute("""
        UPDATE behavior_metric 
        SET user_id = m.owner_id
        FROM metric m 
        WHERE behavior_metric.metric_id = m.id 
        AND behavior_metric.user_id IS NULL
        AND m.owner_id IS NOT NULL
    """)

    # Add NOT NULL constraints to prevent future issues
    op.alter_column("behavior_metric", "organization_id", nullable=False)
    op.alter_column("behavior_metric", "user_id", nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_organization_id", table_name="tool")
    op.drop_index("ix_tool_status_id", table_name="tool")
    op.drop_index("ix_tool_tool_provider_type_id", table_name="tool")
    op.drop_index("ix_tool_tool_type_id", table_name="tool")
    op.drop_index("ix_tool_user_id", table_name="tool")
    op.alter_column(
        "user",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Remove NOT NULL constraints from behavior_metric table
    op.alter_column("behavior_metric", "organization_id", nullable=True)
    op.alter_column("behavior_metric", "user_id", nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_index("ix_tool_user_id", "tool", ["user_id"], unique=False)
    op.create_index("ix_tool_tool_type_id", "tool", ["tool_type_id"], unique=False)
    op.create_index(
        "ix_tool_tool_provider_type_id", "tool", ["tool_provider_type_id"], unique=False
    )
    op.create_index("ix_tool_status_id", "tool", ["status_id"], unique=False)
    op.create_index("ix_tool_organization_id", "tool", ["organization_id"], unique=False)
    # ### end Alembic commands ###
