from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import rhesis.backend

# revision identifiers, used by Alembic.
revision: str = "952b739375ec"
down_revision: Union[str, None] = "c607e92437c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_test_set",
        sa.Column("test_id", rhesis.app.models.guid.GUID(), nullable=False),
        sa.Column("test_set_id", rhesis.app.models.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_set_id"],
            ["test_set.id"],
        ),
        sa.PrimaryKeyConstraint("test_id", "test_set_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_test_set")
    # ### end Alembic commands ###
