from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a422cd31bbda"
down_revision: Union[str, None] = "adc146598a8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("behavior", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("category", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("demographic", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("dimension", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("endpoint", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("prompt", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("prompt_template", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("response_pattern", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("risk", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("source", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("status", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("subscription", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("tag", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("tagged_item", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("test_configuration", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("test_result", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("test_run", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("test_set", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("topic", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("type_lookup", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("use_case", sa.Column("nano_id", sa.String(), nullable=True))
    op.add_column("user", sa.Column("nano_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "nano_id")
    op.drop_column("use_case", "nano_id")
    op.drop_column("type_lookup", "nano_id")
    op.drop_column("topic", "nano_id")
    op.drop_column("test_set", "nano_id")
    op.drop_column("test_run", "nano_id")
    op.drop_column("test_result", "nano_id")
    op.drop_column("test_configuration", "nano_id")
    op.drop_column("tagged_item", "nano_id")
    op.drop_column("tag", "nano_id")
    op.drop_column("subscription", "nano_id")
    op.drop_column("status", "nano_id")
    op.drop_column("source", "nano_id")
    op.drop_column("risk", "nano_id")
    op.drop_column("response_pattern", "nano_id")
    op.drop_column("prompt_template", "nano_id")
    op.drop_column("prompt", "nano_id")
    op.drop_column("endpoint", "nano_id")
    op.drop_column("dimension", "nano_id")
    op.drop_column("demographic", "nano_id")
    op.drop_column("category", "nano_id")
    op.drop_column("behavior", "nano_id")
    # ### end Alembic commands ###
