from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence



# revision identifiers, used by Alembic.
revision: str = 'a652d86ae31c'
down_revision: Union[str, None] = 'ae95a2982195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('auth_token', sa.Text(), nullable=True))
    op.drop_column('endpoint', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('endpoint', 'auth_token')
    # ### end Alembic commands ###