from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence
import rhesis



# revision identifiers, used by Alembic.
revision: str = 'a95dc8bbfd1f'
down_revision: Union[str, None] = 'c5516aad2f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('test_run_id', rhesis.backend.app.models.guid.GUID(), nullable=True))
    op.add_column('trace', sa.Column('test_result_id', rhesis.backend.app.models.guid.GUID(), nullable=True))
    op.add_column('trace', sa.Column('test_id', rhesis.backend.app.models.guid.GUID(), nullable=True))
    op.create_index('idx_trace_test', 'trace', ['test_id'], unique=False)
    op.create_index('idx_trace_test_result', 'trace', ['test_result_id'], unique=False)
    op.create_index('idx_trace_test_run', 'trace', ['test_run_id', sa.literal_column('start_time DESC')], unique=False)
    op.create_index(op.f('ix_trace_test_id'), 'trace', ['test_id'], unique=False)
    op.create_index(op.f('ix_trace_test_result_id'), 'trace', ['test_result_id'], unique=False)
    op.create_index(op.f('ix_trace_test_run_id'), 'trace', ['test_run_id'], unique=False)
    op.create_unique_constraint(None, 'trace', ['nano_id'])
    op.create_foreign_key(None, 'trace', 'test', ['test_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trace', 'test_result', ['test_result_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trace', 'test_run', ['test_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trace', type_='foreignkey')
    op.drop_constraint(None, 'trace', type_='foreignkey')
    op.drop_constraint(None, 'trace', type_='foreignkey')
    op.drop_constraint(None, 'trace', type_='unique')
    op.drop_index(op.f('ix_trace_test_run_id'), table_name='trace')
    op.drop_index(op.f('ix_trace_test_result_id'), table_name='trace')
    op.drop_index(op.f('ix_trace_test_id'), table_name='trace')
    op.drop_index('idx_trace_test_run', table_name='trace')
    op.drop_index('idx_trace_test_result', table_name='trace')
    op.drop_index('idx_trace_test', table_name='trace')
    op.drop_column('trace', 'test_id')
    op.drop_column('trace', 'test_result_id')
    op.drop_column('trace', 'test_run_id')
    # ### end Alembic commands ###