from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence



# revision identifiers, used by Alembic.
revision: str = 'd6a128541142'
down_revision: Union[str, None] = 'a652d86ae31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('last_token', sa.Text(), nullable=True))
    op.add_column('endpoint', sa.Column('last_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint', 'last_token_expires_at')
    op.drop_column('endpoint', 'last_token')
    # ### end Alembic commands ###