from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d89c965e4e8a"
down_revision: Union[str, None] = "d20d7f8d4bbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("token", "expires_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("token", "expires_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###
