from typing import Sequence, Union

import rhesis
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from rhesis.backend.alembic.utils.template_loader import (
    load_cleanup_status_template,
    load_cleanup_type_lookup_template,
    load_status_template,
    load_type_lookup_template,
)

# revision identifiers, used by Alembic.
revision: str = "dc03001dbf24"
down_revision: Union[str, None] = "179eb8de14f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tool_type_id", rhesis.backend.app.models.guid.GUID(), nullable=False),
        sa.Column("tool_provider_type_id", rhesis.backend.app.models.guid.GUID(), nullable=False),
        sa.Column("status_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column(
            "credentials", rhesis.backend.app.utils.encryption.EncryptedString(), nullable=False
        ),
        sa.Column("tool_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id",
            rhesis.backend.app.models.guid.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nano_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("user_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_provider_type_id"],
            ["type_lookup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_type_id"],
            ["type_lookup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_deleted_at"), "tool", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tool_id"), "tool", ["id"], unique=True)
    op.create_index(op.f("ix_tool_organization_id"), "tool", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tool_tool_type_id"), "tool", ["tool_type_id"], unique=False)
    op.create_index(
        op.f("ix_tool_tool_provider_type_id"), "tool", ["tool_provider_type_id"], unique=False
    )
    op.create_index(op.f("ix_tool_status_id"), "tool", ["status_id"], unique=False)
    op.create_index(op.f("ix_tool_user_id"), "tool", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Add new type lookup and status entries for existing organizations
    entity_type_values = """
        ('EntityType', 'Tool', 'Entity type for tools')
    """

    tool_type_values = """
        ('ToolType', 'mcp', 'Model Context Protocol tool'),
        ('ToolType', 'api', 'REST API tool')
    """

    tool_provider_values = """
        ('ToolProviderType', 'notion', 'Notion workspace integration'),
        ('ToolProviderType', 'github', 'GitHub repository integration'),
        ('ToolProviderType', 'atlassian', 'Atlassian integration for Jira and Confluence'),
        ('ToolProviderType', 'custom', 'Custom provider with manual configuration')
    """

    tool_status_values = """
        ('Active', 'Tool is configured and ready', 'Tool'),
        ('Inactive', 'Tool is disabled', 'Tool')
    """

    # Insert EntityType entry for Tool
    entity_type_sql = load_type_lookup_template(entity_type_values)
    op.execute(entity_type_sql)

    # Insert ToolType entries
    tool_type_sql = load_type_lookup_template(tool_type_values)
    op.execute(tool_type_sql)

    # Insert ToolProviderType entries
    tool_provider_sql = load_type_lookup_template(tool_provider_values)
    op.execute(tool_provider_sql)

    # Insert Tool status entries
    tool_status_sql = load_status_template("EntityType", "Tool", tool_status_values)
    op.execute(tool_status_sql)


def downgrade() -> None:
    # Clean up all Tool-related entries before dropping the table
    entity_type_cleanup_values = """
        ('Tool')
    """

    tool_type_cleanup_values = """
        ('mcp'),
        ('api')
    """

    tool_provider_cleanup_values = """
        ('notion'),
        ('github'),
        ('google'),
        ('gdrive'),
        ('custom')
    """

    tool_status_cleanup_values = """
        ('Active'),
        ('Inactive')
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_user_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_status_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_tool_provider_type_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_tool_type_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_organization_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_deleted_at"), table_name="tool")
    op.drop_table("tool")

    # Clean up Tool status entries
    status_cleanup_sql = load_cleanup_status_template(
        "EntityType", "Tool", tool_status_cleanup_values
    )
    op.execute(status_cleanup_sql)

    # Clean up ToolProviderType entries
    provider_cleanup_sql = load_cleanup_type_lookup_template(
        "ToolProviderType", tool_provider_cleanup_values
    )
    op.execute(provider_cleanup_sql)

    # Clean up ToolType entries
    type_cleanup_sql = load_cleanup_type_lookup_template("ToolType", tool_type_cleanup_values)
    op.execute(type_cleanup_sql)

    # Clean up EntityType entry for Tool
    entity_cleanup_sql = load_cleanup_type_lookup_template("EntityType", entity_type_cleanup_values)
    op.execute(entity_cleanup_sql)

    # ### end Alembic commands ###
