from typing import Sequence, Union

import rhesis
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc03001dbf24"
down_revision: Union[str, None] = "179eb8de14f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tool_type_id", rhesis.backend.app.models.guid.GUID(), nullable=False),
        sa.Column("tool_provider_type_id", rhesis.backend.app.models.guid.GUID(), nullable=False),
        sa.Column("status_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column(
            "auth_token", rhesis.backend.app.utils.encryption.EncryptedString(), nullable=False
        ),
        sa.Column("tool_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            rhesis.backend.app.models.guid.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("nano_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("organization_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.Column("user_id", rhesis.backend.app.models.guid.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_provider_type_id"],
            ["type_lookup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_type_id"],
            ["type_lookup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_deleted_at"), "tool", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tool_id"), "tool", ["id"], unique=True)
    op.create_index(op.f("ix_tool_organization_id"), "tool", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tool_tool_type_id"), "tool", ["tool_type_id"], unique=False)
    op.create_index(
        op.f("ix_tool_tool_provider_type_id"), "tool", ["tool_provider_type_id"], unique=False
    )
    op.create_index(op.f("ix_tool_status_id"), "tool", ["status_id"], unique=False)
    op.create_index(op.f("ix_tool_user_id"), "tool", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_user_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_status_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_tool_provider_type_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_tool_type_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_organization_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_id"), table_name="tool")
    op.drop_index(op.f("ix_tool_deleted_at"), table_name="tool")
    op.drop_table("tool")
    # ### end Alembic commands ###
