from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de50496b2a9c"
down_revision: Union[str, None] = "4df7965dfdfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("demographic", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("dimension", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("source", sa.Column("file_path", sa.String(), nullable=True))
    op.add_column("source", sa.Column("file_type", sa.String(), nullable=True))
    op.add_column("source", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("source", sa.Column("file_hash", sa.String(), nullable=True))
    op.add_column("source", sa.Column("uploaded_at", sa.DateTime(), nullable=True))
    op.add_column("source", sa.Column("extracted_content", sa.Text(), nullable=True))
    op.drop_column("source", "language_code")
    op.drop_column("source", "citation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source", sa.Column("citation", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "source",
        sa.Column(
            "language_code",
            sa.VARCHAR(length=5),
            autoincrement=False,
            nullable=True,
            comment="Language in IETF language tag format",
        ),
    )
    op.drop_column("source", "extracted_content")
    op.drop_column("source", "uploaded_at")
    op.drop_column("source", "file_hash")
    op.drop_column("source", "file_size")
    op.drop_column("source", "file_type")
    op.drop_column("source", "file_path")
    op.alter_column("dimension", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("demographic", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
