from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfc884bee642"
down_revision: Union[str, None] = "3a611474f360"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_organization_owner_id_user", "organization", type_="foreignkey")
    op.drop_constraint("fk_organization_user_id_user", "organization", type_="foreignkey")
    op.create_foreign_key(None, "organization", "user", ["owner_id"], ["id"])
    op.create_foreign_key(None, "organization", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.create_foreign_key(
        "fk_organization_user_id_user",
        "organization",
        "user",
        ["user_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        "fk_organization_owner_id_user",
        "organization",
        "user",
        ["owner_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###
