from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f87e36837d0b"
down_revision: Union[str, None] = "3f1af206ee7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("given_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("family_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("picture", sa.String(), nullable=True))
    op.add_column("user", sa.Column("auth0_id", sa.String(), nullable=True))
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("user", "auth0_id")
    op.drop_column("user", "picture")
    op.drop_column("user", "family_name")
    op.drop_column("user", "given_name")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
