{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    tier: frontend
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: frontend
    tier: frontend
{{- end }}
