# Standalone stg network (no peering). For full deploy with peerings run from infrastructure/

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
  backend "gcs" {
    prefix = "terraform/infrastructure/envs/stg"
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

module "stg" {
  source = "../../modules/network/gcp"

  project_id         = var.project_id
  environment        = "stg"
  region             = var.region
  network_cidr       = local.cidrs.stg.network
  create_gke_subnets = true
  node_cidr          = local.cidrs.stg.nodes
  ilb_cidr           = local.cidrs.stg.ilb
  master_cidr        = local.cidrs.stg.master
  pod_cidr           = local.cidrs.stg.pods
  service_cidr       = local.cidrs.stg.services
}

module "gke_stg" {
  source = "../../modules/kubernetes/gcp"

  project_id             = var.project_id
  environment            = "stg"
  region                 = var.region
  vpc_name               = module.stg.vpc_name
  nodes_subnet_self_link = module.stg.subnet_self_links["nodes"]
  master_cidr            = local.cidrs.stg.master
  node_cidr              = local.cidrs.stg.nodes
  pod_cidr               = local.cidrs.stg.pods
  service_cidr           = local.cidrs.stg.services
  wireguard_cidr         = local.cidrs.wireguard.network
  machine_type           = "e2-standard-2"
  min_node_count         = 1
  max_node_count         = 3
  deletion_protection    = var.gke_deletion_protection

  depends_on = [module.stg]
}

module "eso_stg" {
  source = "../../modules/external-secrets/gcp"

  project_id  = var.project_id
  environment = "stg"

  depends_on = [module.gke_stg]
}

module "external_dns_stg" {
  source = "../../modules/external-dns/gcp"

  project_id  = var.project_id
  environment = "stg"

  depends_on = [module.eso_stg]
}

module "internal_dns_stg" {
  source = "../../modules/internal-dns/gcp"

  project_id  = var.project_id
  environment = "stg"

  depends_on = [module.eso_stg]
}

module "ingress_stg" {
  source = "../../modules/ingress/gcp"

  project_id           = var.project_id
  environment          = "stg"
  region               = var.region
  ilb_subnet_self_link = module.stg.subnet_self_links["ilb"]
  internal_lb_ip       = local.cidrs.stg.ingress_internal_ip

  depends_on = [module.stg]
}

module "argocd_stg" {
  source = "../../modules/argocd"

  project_id   = var.project_id
  region       = var.region
  cluster_name = module.gke_stg.cluster_name
  environment  = "stg"
  repo_root    = abspath("${path.module}/../../../..")

  depends_on = [module.gke_stg]
}

# Generate cluster.env for ingress-nginx-internal (single source of truth)
resource "local_file" "cluster_env_stg" {
  content = <<-EOT
# Generated by Terraform from terraform/infrastructure/envs/stg. Do not edit by hand.
region=${var.region}
ilb-subnet-name=${module.stg.ilb_subnet_name}
internal-lb-ip=${local.cidrs.stg.ingress_internal_ip}
EOT
  filename             = "${path.module}/../../../../kubernetes/clusters/stg/ingress-nginx-internal/cluster.env"
  file_permission      = "0644"
  directory_permission = "0755"
}
