apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: 1b5f20166937136bedeb818353e27db211e967af
    path: kubernetes/clusters/prd/alloy
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
