apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: ab2457f097dfaf83802a442076df77fee41aa351
    path: kubernetes/clusters/prd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
