apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-cluster-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: 104bba6bb0ee8d3023ec00f89dd8cbd717ef3afa
    path: kubernetes/clusters/prd/cluster-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
