apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: aade5e089343000ee54be55c3c209265e8c495a6
    path: kubernetes/clusters/prd/external-dns
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
