apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-grafana-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: a1063f7b5ba89603b2caa4c82a92479c7818780c
    path: kubernetes/clusters/prd/grafana-resources
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
