apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-grafana-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: c1731b0e9adeac97a47259c25ce71ce970097e56
    path: kubernetes/clusters/prd/grafana-resources
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
