apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-grafana-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: 104bba6bb0ee8d3023ec00f89dd8cbd717ef3afa
    path: kubernetes/clusters/prd/grafana-resources
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
