apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-grafana-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: e6bc068019f548699f3daf3b9f78adfec5c1328e
    path: kubernetes/clusters/prd/grafana-operator
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
