apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-internal-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: 01b9ff2241b4dc74846b037d481ea1184669ed1b
    path: kubernetes/clusters/prd/internal-dns
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
