apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cnpg-system

patches:
  - path: cnpg-operator-automated-sync.yaml
  - path: cnpg-operator-helm-chart.yaml
