apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: discord-default
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  name: discord-default
  receivers:
    - type: discord
      settings:
        use_discord_username: true
      valuesFrom:
        - targetPath: url
          valueFrom:
            secretKeyRef:
              name: grafana-discord-webhook
              key: url
