name: Setup Python Build
description: Set up Python environment and build tools for PyPI publishing

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install build tools
      shell: bash
      run: pip install build
