{{- if .Values.docs.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: {{ .Release.Namespace }}
  labels:
    app: docs
    tier: docs
    {{- include "rhesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.docs.service.type }}
  ports:
    - port: {{ .Values.docs.service.port }}
      targetPort: {{ .Values.docs.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: docs
    tier: docs
{{- end }}
