#!/bin/bash
# ./rh dev — local development environment: env files, infrastructure containers,
# status, and the tmux session that runs every service at once.

# ============================================================================
# Configuration
# ============================================================================

# Dev ports are deliberately distinct from prod (5432/6379) and test (10001/10002).
DEV_POSTGRES_PORT=11000
DEV_REDIS_PORT=11001

DEV_POSTGRES_CONTAINER="rhesis-dev-postgres"
DEV_REDIS_CONTAINER="rhesis-dev-redis"

DEV_ENV_MARKER="# Generated by ./rh dev init"
DEV_BACKEND_ENV="$SCRIPT_DIR/apps/backend/.env"
DEV_FRONTEND_ENV="$SCRIPT_DIR/apps/frontend/.env.local"

# ============================================================================
# Predicates
# ============================================================================

# True when the env file carries the marker ./rh dev init writes on line 1.
is_dev_generated() {
    local file="$1"
    [ -f "$file" ] && head -n1 "$file" | grep -qF "$DEV_ENV_MARKER"
}

check_env_files_exist() {
    [ -f "$DEV_BACKEND_ENV" ] && [ -f "$DEV_FRONTEND_ENV" ]
}

# True when a container of this name is up.
dev_container_running() {
    docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^$1\$"
}

# ============================================================================
# Env file creation
# ============================================================================

# Confirm before clobbering an env file we did not write.
prompt_overwrite() {
    local file="$1"
    warn "File exists: $file"
    step "   This file was NOT generated by ./rh dev init."
    confirm "Overwrite?"
}

# Shared preamble for create_backend_env / create_frontend_env: bail out (0) when
# the user declines to overwrite a hand-written file, otherwise announce and proceed.
dev_env_writable() {
    local env_file="$1"
    if [ -f "$env_file" ] && ! is_dev_generated "$env_file"; then
        if ! prompt_overwrite "$env_file"; then
            info "   Skipping $env_file"
            return 1
        fi
    fi
    echo -e "${GREEN}Creating $env_file${NC}"
    return 0
}

create_backend_env() {
    local env_file="$DEV_BACKEND_ENV"
    local encryption_key="$1"
    local jwt_secret="$2"
    local session_secret="$3"
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    dev_env_writable "$env_file" || return 0

    cat > "$env_file" << EOF
$DEV_ENV_MARKER on $timestamp

QUICK_START=true

# Database
DB_HOST=localhost
DB_NAME=rhesis-db
DB_PORT=${DEV_POSTGRES_PORT}
APP_DB_USER=rhesis-user
APP_DB_PASS=rhesis-password
DB_ENCRYPTION_KEY=${encryption_key}

# Redis (dev ports)
BROKER_URL=redis://:rhesis-redis-pass@localhost:${DEV_REDIS_PORT}/0
CELERY_RESULT_BACKEND=redis://:rhesis-redis-pass@localhost:${DEV_REDIS_PORT}/1

# Environment
BACKEND_ENV=local
DEV_MODE=true
LOG_LEVEL=DEBUG
OTEL_RHESIS_TELEMETRY_ENABLED=false

# JWT
JWT_SECRET_KEY=${jwt_secret}

# Session
SESSION_SECRET_KEY=${session_secret}

# Rhesis API Key (get one at https://app.rhesis.ai)
RHESIS_API_KEY=your_api_key
EOF
}

create_frontend_env() {
    local env_file="$DEV_FRONTEND_ENV"
    local nextauth_secret="$1"
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    dev_env_writable "$env_file" || return 0

    cat > "$env_file" << EOF
$DEV_ENV_MARKER on $timestamp

API_BASE_URL=http://localhost:8080
FRONTEND_ENV=local
BACKEND_URL=http://localhost:8080
FRONTEND_URL=http://localhost:3000
NEXTAUTH_SECRET=${nextauth_secret}
NEXT_TELEMETRY_DISABLED=1
EOF
}

# ============================================================================
# ./rh dev init
# ============================================================================

dev_init() {
    echo -e "${GREEN}Initializing Rhesis Development Environment...${NC}"
    echo ""

    cd_or_die "$SCRIPT_DIR" "Script"
    check_docker

    if check_env_files_exist; then
        warn "Environment files already exist:"
        echo -e "   - ${BLUE}apps/backend/.env${NC}"
        echo -e "   - ${BLUE}apps/frontend/.env.local${NC}"
        echo ""
        step "Consider backing up these files before continuing if they contain"
        step "   custom configuration or secrets you want to preserve."
        echo ""
        if ! confirm "Do you want to reinitialize? This will overwrite existing files."; then
            echo ""
            ok "Keeping existing configuration"
            return 0
        fi
        echo ""
    fi

    step "Generating encryption key..."
    local encryption_key
    encryption_key=$(gen_secret generate_encryption_key "encryption key") || exit 1
    ok "Encryption key generated"

    step "Generating JWT/session/NextAuth secrets..."
    local jwt_secret session_secret nextauth_secret
    jwt_secret=$(gen_secret generate_hex_secret "JWT secret") || exit 1
    session_secret=$(gen_secret generate_hex_secret "session secret") || exit 1
    nextauth_secret=$(gen_secret generate_hex_secret "NextAuth secret") || exit 1
    ok "Secrets generated"

    echo ""
    step "Creating environment files..."
    create_backend_env "$encryption_key" "$jwt_secret" "$session_secret"
    create_frontend_env "$nextauth_secret"

    echo ""
    rule
    ok "Environment files created!"
    rule
    echo ""
    head1 "Created files:"
    echo -e "   - ${WHITE}apps/backend/.env${NC}"
    echo -e "   - ${WHITE}apps/frontend/.env.local${NC}"
    echo ""
    head1 "Next step:"
    echo -e "   ${GREEN}./rh dev up${NC}  # Start dev infrastructure (postgres, redis)"
    echo ""
}

# ============================================================================
# ./rh dev up
# ============================================================================

dev_up() {
    echo -e "${GREEN}Starting Rhesis Development Infrastructure...${NC}"
    echo ""

    cd_or_die "$SCRIPT_DIR" "Script"

    check_docker
    check_uv
    check_node

    if ! check_env_files_exist; then
        err "Environment files not found!"
        echo ""
        step "Please run initialization first:"
        echo -e "   ${GREEN}./rh dev init${NC}"
        echo ""
        head1 "This will create the following files:"
        echo -e "   - ${WHITE}apps/backend/.env${NC}"
        echo -e "   - ${WHITE}apps/frontend/.env.local${NC}"
        echo ""
        exit 1
    fi

    # Hand-written env files tend to point at the prod ports, which silently
    # connects the dev server to the wrong database. Require the marker.
    if ! is_dev_generated "$DEV_BACKEND_ENV" || ! is_dev_generated "$DEV_FRONTEND_ENV"; then
        err "Environment files exist but were not created by ./rh dev init"
        echo -e "   - ${BLUE}apps/backend/.env${NC}"
        echo -e "   - ${BLUE}apps/frontend/.env.local${NC}"
        echo ""
        step "Using manually created files may cause port or configuration mismatches."
        step "Please initialize proper dev environment files first:"
        echo -e "   ${GREEN}./rh dev init${NC}"
        echo ""
        exit 1
    fi

    step "Starting dev containers (postgres:${DEV_POSTGRES_PORT}, redis:${DEV_REDIS_PORT})..."

    # Restart the existing container if there is one, otherwise create it.
    docker start "$DEV_POSTGRES_CONTAINER" 2>/dev/null || \
    docker run -d \
        --name "$DEV_POSTGRES_CONTAINER" \
        -e POSTGRES_DB=rhesis-db \
        -e POSTGRES_USER=rhesis-user \
        -e POSTGRES_PASSWORD=rhesis-password \
        -p ${DEV_POSTGRES_PORT}:5432 \
        mirror.gcr.io/pgvector/pgvector:pg16

    docker start "$DEV_REDIS_CONTAINER" 2>/dev/null || \
    docker run -d \
        --name "$DEV_REDIS_CONTAINER" \
        -p ${DEV_REDIS_PORT}:6379 \
        mirror.gcr.io/library/redis:7-alpine \
        redis-server --requirepass rhesis-redis-pass

    info "Waiting for PostgreSQL to be ready..."
    for _ in {1..30}; do
        if docker exec "$DEV_POSTGRES_CONTAINER" pg_isready -U rhesis-user -d rhesis-db > /dev/null 2>&1; then
            ok "PostgreSQL is ready"
            break
        fi
        sleep 1
    done

    echo ""
    rule
    ok "Development infrastructure ready!"
    rule
    echo ""
    head1 "Running services:"
    echo -e "   PostgreSQL: ${WHITE}localhost:${DEV_POSTGRES_PORT}${NC}"
    echo -e "   Redis:      ${WHITE}localhost:${DEV_REDIS_PORT}${NC}"
    echo -e "   ${BLUE}Run ${GREEN}./rh dev status${BLUE} to check environment anytime${NC}"
    echo ""
    head1 "Start services:"
    echo -e "   ${GREEN}./rh dev backend${NC}   or  ${GREEN}cd apps/backend && ./start.sh${NC}"
    echo -e "   ${GREEN}./rh dev frontend${NC}  or  ${GREEN}cd apps/frontend && ./start.sh${NC}"
    echo -e "   ${GREEN}./rh dev worker${NC}    or  ${GREEN}cd apps/worker && ./start.sh${NC} (optional)"
    echo ""
    step "Stop infrastructure (postgres, redis):"
    echo -e "   ${GREEN}./rh dev down${NC}    # Stop containers"
    echo -e "   ${GREEN}./rh dev clean${NC}   # Remove containers and volumes (resets database)"
    echo ""
}

# ============================================================================
# ./rh dev down / clean
# ============================================================================

dev_down() {
    step "Stopping Rhesis Development Infrastructure..."
    echo ""

    docker stop "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true
    docker rm "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true

    ok "Development infrastructure stopped"
    echo ""
    head1 "To start again:"
    echo -e "   ${GREEN}./rh dev up${NC}"
    echo ""
}

dev_clean() {
    echo -e "${RED}Cleaning Rhesis Development Infrastructure...${NC}"
    echo ""
    step "This will remove:"
    echo -e "   - Dev containers (${DEV_POSTGRES_CONTAINER}, ${DEV_REDIS_CONTAINER})"
    echo -e "   - Associated Docker volumes (DATABASE DATA WILL BE LOST!)"
    echo ""
    if ! confirm "Are you sure?"; then
        echo ""
        ok "Clean cancelled"
        return 0
    fi
    echo ""

    step "Stopping containers..."
    docker stop "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true

    step "Removing containers..."
    docker rm "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true

    step "Removing volumes..."
    docker volume rm rhesis-dev-postgres-data 2>/dev/null || true
    docker volume rm rhesis-dev-redis-data 2>/dev/null || true

    # Sweep up anonymous volumes the containers may have created.
    docker volume ls -q --filter "name=rhesis-dev" 2>/dev/null | xargs -r docker volume rm 2>/dev/null || true

    echo ""
    ok "Development infrastructure cleaned"
    echo ""
    head1 "To set up again:"
    echo -e "   ${GREEN}./rh dev up${NC}    # Start fresh containers"
    echo ""
}

# ============================================================================
# ./rh dev status
# ============================================================================

# One "✅ apps/backend/.env (initialized: …)" line.
report_env_file() {
    local file="$1"
    local label="$2"
    if [ ! -f "$file" ]; then
        echo -e "   ${RED}❌${NC} $label (missing)"
        return
    fi
    if is_dev_generated "$file"; then
        local created_at
        created_at=$(head -n1 "$file" | sed 's/.*on //')
        echo -e "   ${GREEN}✅${NC} $label (initialized: $created_at)"
    else
        echo -e "   ${GREEN}✅${NC} $label (manually created)"
    fi
}

# One "PostgreSQL: ✅ Running (localhost:11000)" line.
report_container() {
    local container="$1"
    local label="$2"
    local port="$3"
    if dev_container_running "$container"; then
        echo -e "   ${label} ${GREEN}✅ Running${NC} (localhost:${port})"
    else
        echo -e "   ${label} ${RED}Stopped${NC}"
    fi
}

dev_status() {
    head1 "Rhesis Development Environment Status"
    rule
    echo ""

    step "Environment Files:"
    report_env_file "$DEV_BACKEND_ENV" "apps/backend/.env"
    report_env_file "$DEV_FRONTEND_ENV" "apps/frontend/.env.local"
    echo ""

    step "Infrastructure:"
    report_container "$DEV_POSTGRES_CONTAINER" "PostgreSQL:" "$DEV_POSTGRES_PORT"
    report_container "$DEV_REDIS_CONTAINER" "Redis:     " "$DEV_REDIS_PORT"
    echo ""

    if ! check_env_files_exist; then
        step "Next step:"
        echo -e "   ${GREEN}./rh dev init${NC}  # Initialize environment files"
    elif ! dev_container_running "$DEV_POSTGRES_CONTAINER"; then
        step "Next step:"
        echo -e "   ${GREEN}./rh dev up${NC}    # Start dev infrastructure"
    else
        step "Start services:"
        echo -e "   ${GREEN}./rh dev backend${NC}   # Start backend"
        echo -e "   ${GREEN}./rh dev frontend${NC}  # Start frontend"
        echo -e "   ${GREEN}./rh dev worker${NC}    # Start worker (optional)"
    fi
    echo ""
}

# ============================================================================
# ./rh dev tmux
# ============================================================================

DEV_TMUX_SESSION="rhesis"

# Open one tmux window running `./rh dev <service>`. Pass "new" as the third
# argument for the first window, which creates the session.
dev_tmux_window() {
    local name="$1"
    local service="$2"
    if [ "$3" = "new" ]; then
        tmux new-session -d -s "$DEV_TMUX_SESSION" -n "$name" -c "$SCRIPT_DIR"
    else
        tmux new-window -t "$DEV_TMUX_SESSION" -n "$name" -c "$SCRIPT_DIR"
    fi
    tmux send-keys -t "$DEV_TMUX_SESSION:$name" "$SCRIPT_DIR/rh dev $service" C-m
}

dev_tmux() {
    require_cmd tmux "Install tmux and try again (e.g. brew install tmux)"

    cd_or_die "$SCRIPT_DIR" "Script"

    if ! check_env_files_exist; then
        err "Environment files not found!"
        echo -e "${YELLOW}   Run ${GREEN}./rh dev init${YELLOW} then ${GREEN}./rh dev up${YELLOW} first${NC}"
        exit 1
    fi

    if ! dev_container_running "$DEV_POSTGRES_CONTAINER"; then
        step "Dev infrastructure not running — starting postgres and redis..."
        dev_up
    fi

    if tmux has-session -t "$DEV_TMUX_SESSION" 2>/dev/null; then
        info "Attaching to existing tmux session: ${DEV_TMUX_SESSION}"
        exec tmux attach-session -t "$DEV_TMUX_SESSION"
    fi

    echo -e "${GREEN}Starting tmux session: ${DEV_TMUX_SESSION}${NC}"
    info "Windows: backend, frontend, worker, llm, chatbot"
    echo ""

    dev_tmux_window backend backend new
    dev_tmux_window frontend frontend
    dev_tmux_window worker worker
    dev_tmux_window llm mock-llm
    dev_tmux_window chatbot mock-chatbot

    tmux select-window -t "$DEV_TMUX_SESSION:backend"

    exec tmux attach-session -t "$DEV_TMUX_SESSION"
}

# ============================================================================
# ./rh dev seed
# ============================================================================

# Create the mock LLM model + mock chatbot endpoint if they are missing.
# Idempotent. Talks to the running backend over HTTP using the Quick Start local
# token, so it touches no backend app code.
seed_dev_resources() {
    local script="$SCRIPT_DIR/apps/developer-tools/seed_dev_resources.sh"
    if [ -f "$script" ]; then
        bash "$script"
    else
        warn "Seed script not found: $script"
        return 1
    fi
}
