#!/bin/bash
# ./rh dev — local development environment.

# ============================================================================
# Configuration
# ============================================================================

# Ports live in ports.sh, which ./rh sources ahead of this file.

DEV_POSTGRES_CONTAINER="${RHESIS_DEV_PREFIX}-postgres"
DEV_REDIS_CONTAINER="${RHESIS_DEV_PREFIX}-redis"

# Named volumes, not the containers' writable layers, so ./rh dev down can stop
# without discarding the database. Only ./rh dev clean removes them.
DEV_POSTGRES_VOLUME="${RHESIS_DEV_PREFIX}-postgres-data"
DEV_REDIS_VOLUME="${RHESIS_DEV_PREFIX}-redis-data"

DEV_ENV_MARKER="# Generated by ./rh dev init"
DEV_BACKEND_ENV="$SCRIPT_DIR/apps/backend/.env"
DEV_FRONTEND_ENV="$SCRIPT_DIR/apps/frontend/.env.local"

# ============================================================================
# Predicates
# ============================================================================

is_dev_generated() {
    local file="$1"
    [ -f "$file" ] && head -n1 "$file" | grep -qF "$DEV_ENV_MARKER"
}

check_env_files_exist() {
    [ -f "$DEV_BACKEND_ENV" ] && [ -f "$DEV_FRONTEND_ENV" ]
}

dev_container_running() {
    docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^$1\$"
}

report_worktree() {
    echo -e "   Worktree:   ${WHITE}${RHESIS_WORKTREE_NAME:-main}${NC} (offset ${RHESIS_PORT_OFFSET})"
    echo -e "   Frontend:   ${WHITE}http://localhost:${DEV_FRONTEND_PORT}${NC}"
    echo -e "   Backend:    ${WHITE}http://localhost:${DEV_BACKEND_PORT}/docs${NC}"
    echo -e "   Flower:     ${WHITE}http://localhost:${DEV_FLOWER_PORT}${NC}"
}

# A worktree made with bare `git worktree add` has no .rhesis-ports, so it would
# share main's ports and containers.
warn_unregistered_worktree() {
    [ -n "$RHESIS_WORKTREE_NAME" ] && return 0

    local main_worktree
    main_worktree=$(git -C "$SCRIPT_DIR" worktree list --porcelain 2>/dev/null | head -n1)
    main_worktree="${main_worktree#worktree }"
    if [ -z "$main_worktree" ] || [ "$main_worktree" = "$SCRIPT_DIR" ]; then
        return 0
    fi

    warn "No .rhesis-ports here — this checkout shares main's ports and containers"
    step "   Create worktrees with ${GREEN}./rh worktree <name>${NC}${YELLOW} to get their own${NC}"
    echo ""
}

# ============================================================================
# Env file creation
# ============================================================================

prompt_overwrite() {
    local file="$1"
    warn "File exists: $file"
    step "   This file was NOT generated by ./rh dev init."
    confirm "Overwrite?"
}

# Returns non-zero when the user declines to overwrite a hand-written file.
dev_env_writable() {
    local env_file="$1"
    if [ -f "$env_file" ] && ! is_dev_generated "$env_file"; then
        if ! prompt_overwrite "$env_file"; then
            info "   Skipping $env_file"
            return 1
        fi
    fi
    echo -e "${GREEN}Creating $env_file${NC}"
    return 0
}

create_backend_env() {
    local env_file="$DEV_BACKEND_ENV"
    local encryption_key="$1"
    local jwt_secret="$2"
    local session_secret="$3"
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    dev_env_writable "$env_file" || return 0

    cat > "$env_file" << EOF
$DEV_ENV_MARKER on $timestamp

QUICK_START=true

# Server (start.sh reads PORT from here)
PORT=${DEV_BACKEND_PORT}

# The backend's CORS allowlist is derived from this single value
# (config/settings.py::cors_origins). Unset, it defaults to localhost:3000,
# which only matches a worktree running on the base port block -- every other
# worktree gets its browser requests rejected as a disallowed origin.
FRONTEND_URL=http://localhost:${DEV_FRONTEND_PORT}

# Database
DB_HOST=localhost
DB_NAME=rhesis-db
DB_PORT=${DEV_POSTGRES_PORT}
APP_DB_USER=rhesis-user
APP_DB_PASS=rhesis-password
DB_ENCRYPTION_KEY=${encryption_key}

# Redis (dev ports)
BROKER_URL=redis://:rhesis-redis-pass@localhost:${DEV_REDIS_PORT}/0
CELERY_RESULT_BACKEND=redis://:rhesis-redis-pass@localhost:${DEV_REDIS_PORT}/1

# Environment
BACKEND_ENV=local
DEV_MODE=true
LOG_LEVEL=DEBUG
OTEL_RHESIS_TELEMETRY_ENABLED=false

# JWT
JWT_SECRET_KEY=${jwt_secret}

# Session
SESSION_SECRET_KEY=${session_secret}

# Rhesis API Key (get one at https://app.rhesis.ai)
RHESIS_API_KEY=your_api_key
EOF
}

create_frontend_env() {
    local env_file="$DEV_FRONTEND_ENV"
    local nextauth_secret="$1"
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    dev_env_writable "$env_file" || return 0

    cat > "$env_file" << EOF
$DEV_ENV_MARKER on $timestamp

API_BASE_URL=http://localhost:${DEV_BACKEND_PORT}
FRONTEND_ENV=local
BACKEND_URL=http://localhost:${DEV_BACKEND_PORT}

# FRONTEND_URL is also NextAuth's base URL (src/auth.ts), so it tracks PORT.
FRONTEND_URL=http://localhost:${DEV_FRONTEND_PORT}
PORT=${DEV_FRONTEND_PORT}

NEXTAUTH_SECRET=${nextauth_secret}
NEXT_TELEMETRY_DISABLED=1

# Docs cards shown on the Architect welcome screen while a project has no
# endpoint. Read at request time by /api/architect-help; in the cloud it comes
# from GCP Secret Manager instead. Hosts must be allowlisted in
# apps/frontend/src/app/api/og-metadata/og-metadata-utils.ts.
ARCHITECT_HELP_ARTICLE_URLS=https://docs.rhesis.ai/docs/getting-started/connecting-application,https://docs.rhesis.ai/docs/endpoints,https://docs.rhesis.ai/docs/endpoints/sdk-endpoints,https://docs.rhesis.ai/docs/concepts
EOF
}

# ============================================================================
# ./rh dev init
# ============================================================================

dev_init() {
    echo -e "${GREEN}Initializing Rhesis Development Environment...${NC}"
    echo ""

    cd_or_die "$SCRIPT_DIR" "Script"
    check_docker

    if check_env_files_exist; then
        warn "Environment files already exist:"
        echo -e "   - ${BLUE}apps/backend/.env${NC}"
        echo -e "   - ${BLUE}apps/frontend/.env.local${NC}"
        echo ""
        step "Consider backing up these files before continuing if they contain"
        step "   custom configuration or secrets you want to preserve."
        echo ""
        if ! confirm "Do you want to reinitialize? This will overwrite existing files."; then
            echo ""
            ok "Keeping existing configuration"
            return 0
        fi
        echo ""
    fi

    step "Generating encryption key..."
    local encryption_key
    encryption_key=$(gen_secret generate_encryption_key "encryption key") || exit 1
    ok "Encryption key generated"

    step "Generating JWT/session/NextAuth secrets..."
    local jwt_secret session_secret nextauth_secret
    jwt_secret=$(gen_secret generate_hex_secret "JWT secret") || exit 1
    session_secret=$(gen_secret generate_hex_secret "session secret") || exit 1
    nextauth_secret=$(gen_secret generate_hex_secret "NextAuth secret") || exit 1
    ok "Secrets generated"

    echo ""
    step "Creating environment files..."
    create_backend_env "$encryption_key" "$jwt_secret" "$session_secret"
    create_frontend_env "$nextauth_secret"

    echo ""
    rule
    ok "Environment files created!"
    rule
    echo ""
    head1 "Created files:"
    echo -e "   - ${WHITE}apps/backend/.env${NC}"
    echo -e "   - ${WHITE}apps/frontend/.env.local${NC}"
    echo ""
    head1 "Next step:"
    echo -e "   ${GREEN}./rh dev up${NC}  # Start dev infrastructure (postgres, redis)"
    echo ""
}

# ============================================================================
# ./rh dev up
# ============================================================================

dev_up() {
    echo -e "${GREEN}Starting Rhesis Development Infrastructure...${NC}"
    echo ""

    cd_or_die "$SCRIPT_DIR" "Script"

    warn_unregistered_worktree

    check_docker
    check_uv
    check_node

    if ! check_env_files_exist; then
        err "Environment files not found!"
        echo ""
        step "Please run initialization first:"
        echo -e "   ${GREEN}./rh dev init${NC}"
        echo ""
        head1 "This will create the following files:"
        echo -e "   - ${WHITE}apps/backend/.env${NC}"
        echo -e "   - ${WHITE}apps/frontend/.env.local${NC}"
        echo ""
        exit 1
    fi

    # Hand-written env files tend to point at the prod ports, which silently
    # connects the dev server to the wrong database. Require the marker.
    if ! is_dev_generated "$DEV_BACKEND_ENV" || ! is_dev_generated "$DEV_FRONTEND_ENV"; then
        err "Environment files exist but were not created by ./rh dev init"
        echo -e "   - ${BLUE}apps/backend/.env${NC}"
        echo -e "   - ${BLUE}apps/frontend/.env.local${NC}"
        echo ""
        step "Using manually created files may cause port or configuration mismatches."
        step "Please initialize proper dev environment files first:"
        echo -e "   ${GREEN}./rh dev init${NC}"
        echo ""
        exit 1
    fi

    step "Starting dev containers (postgres:${DEV_POSTGRES_PORT}, redis:${DEV_REDIS_PORT})..."

    # A container predating the volumes keeps its writable-layer data: docker
    # start reuses it, and it only picks up the volume after ./rh dev clean.
    docker start "$DEV_POSTGRES_CONTAINER" 2>/dev/null || \
    docker run -d \
        --name "$DEV_POSTGRES_CONTAINER" \
        -e POSTGRES_DB=rhesis-db \
        -e POSTGRES_USER=rhesis-user \
        -e POSTGRES_PASSWORD=rhesis-password \
        -p ${DEV_POSTGRES_PORT}:5432 \
        -v "$DEV_POSTGRES_VOLUME":/var/lib/postgresql/data \
        mirror.gcr.io/pgvector/pgvector:pg16

    docker start "$DEV_REDIS_CONTAINER" 2>/dev/null || \
    docker run -d \
        --name "$DEV_REDIS_CONTAINER" \
        -p ${DEV_REDIS_PORT}:6379 \
        -v "$DEV_REDIS_VOLUME":/data \
        mirror.gcr.io/library/redis:7-alpine \
        redis-server --requirepass rhesis-redis-pass

    info "Waiting for PostgreSQL to be ready..."
    local pg_ready=0
    for _ in {1..30}; do
        if docker exec "$DEV_POSTGRES_CONTAINER" pg_isready -U rhesis-user -d rhesis-db > /dev/null 2>&1; then
            pg_ready=1
            ok "PostgreSQL is ready"
            break
        fi
        sleep 1
    done

    # Otherwise the success banner prints over a stack that never came up, and
    # the first visible failure is the backend, far from the cause.
    if [ "$pg_ready" -eq 0 ]; then
        die "Error: PostgreSQL did not become ready within 30s" \
            "Check the logs: docker logs $DEV_POSTGRES_CONTAINER" \
            "Then retry: ./rh dev up"
    fi

    echo ""
    rule
    ok "Development infrastructure ready!"
    rule
    echo ""
    head1 "Running services:"
    echo -e "   PostgreSQL: ${WHITE}localhost:${DEV_POSTGRES_PORT}${NC} (${DEV_POSTGRES_CONTAINER})"
    echo -e "   Redis:      ${WHITE}localhost:${DEV_REDIS_PORT}${NC} (${DEV_REDIS_CONTAINER})"
    report_worktree
    echo -e "   ${BLUE}Run ${GREEN}./rh dev status${BLUE} to check environment anytime${NC}"
    echo ""
    head1 "Start services:"
    echo -e "   ${GREEN}./rh dev backend${NC}   or  ${GREEN}cd apps/backend && ./start.sh${NC}"
    echo -e "   ${GREEN}./rh dev frontend${NC}  or  ${GREEN}cd apps/frontend && ./start.sh${NC}"
    echo -e "   ${GREEN}./rh dev worker${NC}    or  ${GREEN}cd apps/worker && ./start.sh${NC} (optional)"
    echo ""
    step "Stop infrastructure (postgres, redis):"
    echo -e "   ${GREEN}./rh dev down${NC}    # Stop containers (database is kept)"
    echo -e "   ${GREEN}./rh dev clean${NC}   # Remove containers and volumes (resets database)"
    echo ""
}

# ============================================================================
# ./rh dev down / clean
# ============================================================================

# Stop only — removal is ./rh dev clean's job.
dev_down() {
    step "Stopping Rhesis Development Infrastructure..."
    echo ""

    docker stop "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true

    ok "Development infrastructure stopped (database kept)"
    echo ""
    head1 "To start again:"
    echo -e "   ${GREEN}./rh dev up${NC}"
    echo ""
    head1 "To reset the database:"
    echo -e "   ${GREEN}./rh dev clean${NC}"
    echo ""
}

dev_clean() {
    echo -e "${RED}Cleaning Rhesis Development Infrastructure...${NC}"
    echo ""
    step "This will remove:"
    echo -e "   - Dev containers (${DEV_POSTGRES_CONTAINER}, ${DEV_REDIS_CONTAINER})"
    echo -e "   - Associated Docker volumes (DATABASE DATA WILL BE LOST!)"
    echo ""
    if ! confirm "Are you sure?"; then
        echo ""
        ok "Clean cancelled"
        return 0
    fi
    echo ""

    step "Stopping containers..."
    docker stop "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true

    step "Removing containers..."
    docker rm "$DEV_POSTGRES_CONTAINER" "$DEV_REDIS_CONTAINER" 2>/dev/null || true

    # Volumes must go after the containers using them are removed.
    step "Removing volumes..."
    docker volume rm "$DEV_POSTGRES_VOLUME" 2>/dev/null || true
    docker volume rm "$DEV_REDIS_VOLUME" 2>/dev/null || true

    # Catches anonymous volumes from containers that predate the named ones.
    # Filtered by this checkout's prefix so cleaning one spares the others.
    # Guarded instead of xargs -r, which is a GNU extension.
    local leftover_volumes
    leftover_volumes=$(dev_volumes_for_prefix "$RHESIS_DEV_PREFIX")
    if [ -n "$leftover_volumes" ]; then
        echo "$leftover_volumes" | xargs docker volume rm 2>/dev/null || true
    fi

    echo ""
    ok "Development infrastructure cleaned"
    echo ""
    head1 "To set up again:"
    echo -e "   ${GREEN}./rh dev up${NC}    # Start fresh containers"
    echo ""
}

# ============================================================================
# ./rh dev status
# ============================================================================

report_env_file() {
    local file="$1"
    local label="$2"
    if [ ! -f "$file" ]; then
        echo -e "   ${RED}❌${NC} $label (missing)"
        return
    fi
    if is_dev_generated "$file"; then
        local created_at
        created_at=$(head -n1 "$file" | sed 's/.*on //')
        echo -e "   ${GREEN}✅${NC} $label (initialized: $created_at)"
    else
        echo -e "   ${GREEN}✅${NC} $label (manually created)"
    fi
}

report_container() {
    local container="$1"
    local label="$2"
    local port="$3"
    if dev_container_running "$container"; then
        echo -e "   ${label} ${GREEN}✅ Running${NC} (localhost:${port})"
    else
        echo -e "   ${label} ${RED}Stopped${NC}"
    fi
}

dev_status() {
    head1 "Rhesis Development Environment Status"
    rule
    echo ""

    step "Environment Files:"
    report_env_file "$DEV_BACKEND_ENV" "apps/backend/.env"
    report_env_file "$DEV_FRONTEND_ENV" "apps/frontend/.env.local"
    echo ""

    warn_unregistered_worktree

    step "Infrastructure:"
    report_container "$DEV_POSTGRES_CONTAINER" "PostgreSQL:" "$DEV_POSTGRES_PORT"
    report_container "$DEV_REDIS_CONTAINER" "Redis:     " "$DEV_REDIS_PORT"
    report_worktree
    echo ""

    if ! check_env_files_exist; then
        step "Next step:"
        echo -e "   ${GREEN}./rh dev init${NC}  # Initialize environment files"
    elif ! dev_container_running "$DEV_POSTGRES_CONTAINER"; then
        step "Next step:"
        echo -e "   ${GREEN}./rh dev up${NC}    # Start dev infrastructure"
    else
        step "Start services:"
        echo -e "   ${GREEN}./rh dev backend${NC}   # Start backend"
        echo -e "   ${GREEN}./rh dev frontend${NC}  # Start frontend"
        echo -e "   ${GREEN}./rh dev worker${NC}    # Start worker (optional)"
    fi
    echo ""
}

# ============================================================================
# ./rh dev tmux
# ============================================================================

DEV_TMUX_SESSION="rhesis${RHESIS_WORKTREE_NAME:+-$RHESIS_WORKTREE_NAME}"

# Third argument "new" creates the session instead of adding a window to it.
dev_tmux_window() {
    local name="$1"
    local service="$2"
    if [ "$3" = "new" ]; then
        tmux new-session -d -s "$DEV_TMUX_SESSION" -n "$name" -c "$SCRIPT_DIR"
    else
        tmux new-window -t "$DEV_TMUX_SESSION" -n "$name" -c "$SCRIPT_DIR"
    fi
    tmux send-keys -t "$DEV_TMUX_SESSION:$name" "$SCRIPT_DIR/rh dev $service" C-m
}

dev_tmux() {
    require_cmd tmux "Install tmux and try again (e.g. brew install tmux)"

    cd_or_die "$SCRIPT_DIR" "Script"

    if ! check_env_files_exist; then
        err "Environment files not found!"
        echo -e "${YELLOW}   Run ${GREEN}./rh dev init${YELLOW} then ${GREEN}./rh dev up${YELLOW} first${NC}"
        exit 1
    fi

    if ! dev_container_running "$DEV_POSTGRES_CONTAINER"; then
        step "Dev infrastructure not running — starting postgres and redis..."
        dev_up
    fi

    if tmux has-session -t "$DEV_TMUX_SESSION" 2>/dev/null; then
        info "Attaching to existing tmux session: ${DEV_TMUX_SESSION}"
        exec tmux attach-session -t "$DEV_TMUX_SESSION"
    fi

    echo -e "${GREEN}Starting tmux session: ${DEV_TMUX_SESSION}${NC}"
    info "Windows: backend, frontend, worker, llm, chatbot"
    echo ""

    dev_tmux_window backend backend new
    dev_tmux_window frontend frontend
    dev_tmux_window worker worker
    dev_tmux_window llm mock-llm
    dev_tmux_window chatbot mock-chatbot

    tmux select-window -t "$DEV_TMUX_SESSION:backend"

    exec tmux attach-session -t "$DEV_TMUX_SESSION"
}

# ============================================================================
# ./rh dev seed
# ============================================================================

seed_dev_resources() {
    local script="$SCRIPT_DIR/apps/developer-tools/seed_dev_resources.sh"
    if [ -f "$script" ]; then
        # The script has its own 8080 default; point it at our backend.
        API_BASE_URL="${API_BASE_URL:-http://localhost:${DEV_BACKEND_PORT}}" bash "$script"
    else
        warn "Seed script not found: $script"
        return 1
    fi
}
