"""
Test Configuration Generator Service.

This service handles the generation of test configurations based on user prompts
using LLM and Jinja2 templates.
"""

import logging
from pathlib import Path
from typing import Optional

import jinja2

from rhesis.backend.app.config.settings import get_model_settings
from rhesis.backend.app.constants import BEHAVIOR_LIST_KEY
from rhesis.backend.app.crud import behavior as behavior_crud
from rhesis.backend.app.crud import model as model_crud
from rhesis.backend.app.crud.project import get_project
from rhesis.backend.app.schemas.services import TestConfigResponse
from rhesis.backend.app.utils.model_errors import ModelConfigurationError
from rhesis.backend.app.utils.user_model_utils import (
    ensure_language_model,
    get_user_generation_model,
)

MAX_SAMPLE_SIZE = 6
logger = logging.getLogger(__name__)


class TestConfigGeneratorService:
    """Service for generating test configurations from user prompts."""

    def __init__(self, db, user):
        """Initialize the service with template environment.

        Args:
            max_sample_size: Maximum allowed sample size per category (default: 20)
        """
        self.template_dir = Path(__file__).parent.parent / "templates"
        self.jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(self.template_dir)),
            autoescape=jinja2.select_autoescape(),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self.db = db
        self.user = user

        self.llm = self._resolve_llm()

    def _resolve_llm(self):
        """
        Resolve the LLM for test-config generation.

        Use the user's configured generation model except when it is Polyphemus,
        which is too slow for this interactive step; in that case use the fast
        system generation model setting.
        """
        gen_settings = getattr(self.user.settings.models, "generation")
        model_id = gen_settings.model_id
        use_fast_default = False
        if model_id:
            row = model_crud.get_model(
                db=self.db,
                model_id=str(model_id),
                organization_id=str(self.user.organization_id),
            )
            if row and row.provider_type and row.provider_type.type_value == "polyphemus":
                use_fast_default = True
        if use_fast_default:
            logger.info(
                "User generation model is Polyphemus; using fast system default for test config"
            )
            try:
                # ensure_language_model, not resolve_default_hosted_model:
                # this caller *wants* the raising variant, so a system default
                # that cannot be built falls through to the user's model
                # below. Wrapping resolve's non-raising fallback in ensure
                # just built the same model twice on the failure path.
                return ensure_language_model(get_model_settings().generation_model)
            except ValueError as e:
                logger.warning(
                    "Fast system default unavailable for test config (Polyphemus user); "
                    "falling back to Polyphemus: %s",
                    e,
                )
                try:
                    return ensure_language_model(get_user_generation_model(self.db, self.user))
                except ValueError as inner:
                    raise ModelConfigurationError(
                        f"User model initialization failed: {inner}",
                        original_error=inner,
                    ) from inner

        try:
            return ensure_language_model(get_user_generation_model(self.db, self.user))
        except ValueError as e:
            raise ModelConfigurationError(
                f"User model initialization failed: {e}",
                original_error=e,
            ) from e

    async def generate_config(
        self,
        prompt: str,
        organization_id: Optional[str] = None,
        project_id: Optional[str] = None,
        previous_messages: Optional[list] = None,
    ) -> TestConfigResponse:
        """
        Generate test configuration based on user prompt.

        Behaviors are fetched from the database and the LLM selects which ones are relevant.
        Topics and categories are generated by the LLM.
        If project_id is provided, project details are fetched and included for context.

        Args:
            prompt: User description of what they want to test
            db: Database session for fetching behaviors and project
            organization_id: Organization ID for filtering behaviors and project
            project_id: Optional project ID to include project context

        Returns:
            TestConfigResponse: Generated test configuration with LLM-selected behaviors and
                generated topics/categories

        Raises:
            ValueError: If prompt is empty or invalid, or if db/organization_id not provided,
                or if project_id is provided but project not found
            RuntimeError: If LLM response cannot be parsed
        """
        if not prompt or not prompt.strip():
            raise ValueError("Prompt cannot be empty")

        if self.db is None or organization_id is None:
            raise ValueError("Database session and organization_id are required")

        # Fetch behaviors from database (limited to max 100 by validation)
        behaviors = behavior_crud.get_behaviors(
            db=self.db,
            organization_id=organization_id,
            skip=0,
            limit=100,  # Maximum allowed by validation
        )

        # Convert behaviors to dict format for template
        behavior_list = [
            {"name": behavior.name, "description": behavior.description or ""}
            for behavior in behaviors
        ]

        # Fetch project details if project_id is provided
        project_name = None
        project_description = None
        if project_id:
            project = get_project(
                db=self.db, project_id=project_id, organization_id=organization_id
            )
            if not project:
                raise ValueError(f"Project with id {project_id} not found or not accessible")
            project_name = project.name
            project_description = project.description

        # Render template with user prompt, sample size, behaviors, and project context
        template = self.jinja_env.get_template("test_config_generator.jinja2")

        # If there are previous messages, use the maximum sample size, otherwise let LLM decide.

        rendered_prompt = template.render(
            {
                "prompt": prompt,
                "sample_size": MAX_SAMPLE_SIZE,
                # Must stay in sync with the `{{ behaviors }}` variable in
                # test_config_generator.jinja2 -- the template can't reference this constant.
                BEHAVIOR_LIST_KEY: behavior_list,
                "project_name": project_name,
                "project_description": project_description,
                "previous_messages": previous_messages or [],
            }
        )

        # LLM will select behaviors from the list and generate topics and categories
        llm_response = await self.llm.a_generate(rendered_prompt, schema=TestConfigResponse)

        # SDK providers return {"error": "..."} on failure instead of raising
        if isinstance(llm_response, dict) and "error" in llm_response:
            raise RuntimeError(str(llm_response["error"]))

        # Handle response whether it's a dict or TestConfigResponse object
        if isinstance(llm_response, dict):
            llm_response = TestConfigResponse(**llm_response)

        return llm_response
