apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: rhesis-prd-daily
  namespace: rhesis
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: rhesis-prd
