steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-t', '${_IMAGE_NAME}', 
           '--cache-from', '${_IMAGE_NAME}',
           '.']
    # Enable Docker layer caching
    id: 'build'

# Store the image in Google Container Registry
images:
  - '${_IMAGE_NAME}'

# Use a more powerful machine for builds
options:
  machineType: 'E2_HIGHCPU_8'
  # Avoid rebuilding unchanged layers 
  env:
    - 'DOCKER_BUILDKIT=1'
  
# Set a longer timeout for builds
timeout: '7200s'

# Specify substitution variables that will be filled in by deploy.sh
substitutions:
  _IMAGE_NAME: 'gcr.io/PROJECT_ID/rhesis-polyphemus:latest' 