apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager-application.yaml
  - cluster-issuer-staging.yaml
  - cluster-issuer-prod.yaml
  - cluster-issuer-dns01.yaml
  - cloudflare-cert-api-token.yaml
