repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
          "types-requests",
          "pandas-stubs",
          "pyarrow-stubs",
          "types-tqdm"
        ]

  - repo: local
    hooks:
      - id: poetry-export
        name: poetry-export
        entry: make requirements
        language: system
        pass_filenames: false
        files: ^(pyproject.toml|poetry.lock)$