apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: feat/deploy-kubenetes-inprd
    path: kubernetes/clusters/dev/cluster-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
