apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-grafana-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: main
    path: kubernetes/clusters/dev/grafana-operator
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
