apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/loki

configMapGenerator:
  - name: loki-config
    literals:
      - retention-period=360h
      - storage-size=10Gi
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
      disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: loki-config
      fieldPath: data.retention-period
    targets:
      - select:
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.valuesObject.loki.limits_config.retention_period
  - source:
      kind: ConfigMap
      name: loki-config
      fieldPath: data.storage-size
    targets:
      - select:
          kind: Application
          name: loki
        fieldPaths:
          - spec.source.helm.valuesObject.singleBinary.persistence.size
