# Standalone Dev network (no peering). For full deploy with peerings run from infrastructure/

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
  backend "gcs" {
    prefix = "terraform/infrastructure/envs/dev"
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

module "dev" {
  source = "../../modules/network/gcp"

  project_id         = var.project_id
  environment        = "dev"
  region             = var.region
  network_cidr       = local.cidrs.dev.network
  create_gke_subnets = true
  node_cidr          = local.cidrs.dev.nodes
  ilb_cidr           = local.cidrs.dev.ilb
  master_cidr        = local.cidrs.dev.master
  pod_cidr           = local.cidrs.dev.pods
  service_cidr       = local.cidrs.dev.services
}

module "gke_dev" {
  source = "../../modules/kubernetes/gcp"

  project_id             = var.project_id
  environment            = "dev"
  region                 = var.region
  vpc_name               = module.dev.vpc_name
  nodes_subnet_self_link = module.dev.subnet_self_links["nodes"]
  master_cidr            = local.cidrs.dev.master
  node_cidr              = local.cidrs.dev.nodes
  pod_cidr               = local.cidrs.dev.pods
  service_cidr           = local.cidrs.dev.services
  wireguard_cidr         = local.cidrs.wireguard.network
  machine_type           = "e2-medium"
  min_node_count         = 1
  max_node_count         = 2
  deletion_protection    = var.gke_deletion_protection

  depends_on = [module.dev]
}

module "eso_dev" {
  source = "../../modules/external-secrets/gcp"

  project_id  = var.project_id
  environment = "dev"

  depends_on = [module.gke_dev]
}

module "external_dns_dev" {
  source = "../../modules/external-dns/gcp"

  project_id  = var.project_id
  environment = "dev"

  depends_on = [module.eso_dev]
}

module "internal_dns_dev" {
  source = "../../modules/internal-dns/gcp"

  project_id  = var.project_id
  environment = "dev"

  depends_on = [module.eso_dev]
}

module "ingress_dev" {
  source = "../../modules/ingress/gcp"

  project_id           = var.project_id
  environment          = "dev"
  region               = var.region
  ilb_subnet_self_link = module.dev.subnet_self_links["ilb"]
  internal_lb_ip       = local.cidrs.dev.ingress_internal_ip

  depends_on = [module.dev]
}

# GCS buckets: managed by terraform/infrastructure (root) with the same state as GKE — not duplicated here.
module "argocd_dev" {
  source = "../../modules/argocd"

  project_id   = var.project_id
  region       = var.region
  cluster_name = module.gke_dev.cluster_name
  environment  = "dev"
  repo_root    = abspath("${path.module}/../../../..")

  depends_on = [module.gke_dev]
}

# Generate cluster.env for ingress-nginx-internal (single source of truth)
resource "local_file" "cluster_env_dev" {
  content              = <<-EOT
# Generated by Terraform from terraform/infrastructure/envs/dev. Do not edit by hand.
region=${var.region}
ilb-subnet-name=${module.dev.ilb_subnet_name}
internal-lb-ip=${local.cidrs.dev.ingress_internal_ip}
EOT
  filename             = "${path.module}/../../../../kubernetes/clusters/dev/ingress-nginx-internal/cluster.env"
  file_permission      = "0644"
  directory_permission = "0755"
}
