"""Tools for the Polymath multi-agent system.

Two thin tool packages, kept tiny on purpose so the trace tree generated by
running the workflow stays easy to reason about while still touching every
``ai.tool.invoke`` translator code path in the SDK.
"""

from polymath.tools.info_tools import (
    INFO_TOOLS,
    get_current_time,
    wikipedia_summary,
)
from polymath.tools.math_tools import (
    MATH_TOOLS,
    add,
    multiply,
    power,
    square_root,
)

__all__ = [
    "INFO_TOOLS",
    "MATH_TOOLS",
    "add",
    "get_current_time",
    "multiply",
    "power",
    "square_root",
    "wikipedia_summary",
]
