apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-arc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: feat/self-hosted-runner-workload
    path: kubernetes/clusters/stg/arc
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
