apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-grafana-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/rhesis-ai/rhesis.git
    targetRevision: main
    path: kubernetes/clusters/stg/grafana-resources
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
