name: 'Generate Deployment Summary'
description: 'Generates deployment summary for both regular and preview deployments'
inputs:
  service-type:
    description: 'Service type (Backend, Frontend)'
    required: true
  is-preview:
    description: 'Whether this is a preview deployment'
    required: true
    default: 'false'
  environment:
    description: 'Environment (dev, stg, prd)'
    required: true
  env-display:
    description: 'Human-readable environment name'
    required: true
  service-url:
    description: 'Service URL to display'
    required: true
  actual-service-name:
    description: 'Actual service name extracted from Cloud Run (bypasses obfuscation)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Generate deployment summary
      shell: bash
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ inputs.is-preview }}" = "true" ]; then
          # Preview deployment summary
          echo "## âš ï¸ PREVIEW - ${{ inputs.service-type }} Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Preview URL:** [${{ inputs.service-url }}](${{ inputs.service-url }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Display service name and commit if available
          if [ -n "${{ inputs.actual-service-name }}" ]; then
            echo "**Service:** \`${{ inputs.actual-service-name }}\` | **Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "$GITHUB_SHA" ]; then
            COMMIT_SHORT=${GITHUB_SHA:0:8}
            echo "**Commit:** [\`$COMMIT_SHORT\`](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "âš ï¸ **Preview only** - 0% live traffic, testing purposes only" >> $GITHUB_STEP_SUMMARY
        else
          # Regular deployment summary
          echo "## âœ… ${{ inputs.env-display }} - ${{ inputs.service-type }} Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          
          if [ -n "$GITHUB_SHA" ]; then
            COMMIT_SHORT=${GITHUB_SHA:0:8}
            echo "**Commit:** [\`$COMMIT_SHORT\`](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ inputs.environment }}" = "prd" ]; then
            echo "ðŸš€ **Live deployment** - serving real user traffic" >> $GITHUB_STEP_SUMMARY
          else
            echo "ðŸš€ **Live ${{ inputs.env-display }}** - new revision receiving 100% traffic" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        
        echo "âœ… Deployment summary generated for ${{ inputs.service-type }} (${{ inputs.is-preview == 'true' && 'PREVIEW' || inputs.env-display }})"

